[tool.poetry]
name = "felixlib"
version = "0.0.9"
description = "felixlib"
authors = ["spectereye <spectereye@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7,!=3.7.6"  # python 3.7.6 can't work with pywinauto

[tool.poetry.dev-dependencies]
# this project used as library, place all dependencies in dev below,
# so other project using it can select dependencies really needed below freely
numpy = "^1.17"
flask = "^1.1"
wtforms = "^2.2"
psutil = "^5.6"
pywebview = "^3.1"
pywinauto = "^0.6.8"
xlwings = "^0.16.0"
colorama = "^0.4.1"
pywin32 = "^225"
send2trash = "^1.5"
pysimplegui = "^4.14"

# dependencies for build
cython = "^0.29.14"
pyinstaller = "^3.5"
pywin32-ctypes = "^0.2.0"
pefile = "^2019.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
