[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "layouts"
author = "Jacob Alexander"
author-email = "haata@kiibohd.com"
home-page = "https://github.com/hid-io/layouts-python"
classifiers = ["Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
description-file = "README.md"
requires = ["requests",
    "PyGithub",
    "GitPython",
]
requires-python = ">=3.5"

