[tool.poetry]
name = "where-to"
version = "0.4.0"
description = "Show upcoming Outlook meetings on the Windows lock screen"
authors = ["Blair Conrad <blair@blairconrad.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/blairconrad/where-to.git"


[tool.poetry.scripts]
where-to-console = "where_to.cli:main"

[tool.poetry.plugins."gui_scripts"]
where-to = "where_to.cli:main"

[tool.poetry.dependencies]
python = "^3.7"
pywin32 = "^227"
PILLOW = "^7.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-flake8 = "^1.0.4"
pytest-black = "^0.3.8"
pytest-sugar = "^0.9.2"
taskipy = "^1.1.3"
pytest-mock = "^2.0.0"
pytest-xdist = "^1.31.0"

[tool.black]
line-length = 120
target_version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
    | \.git          # root of the project
    | dist
  )/
)
'''

[tool.taskipy.tasks]
test = "pytest --black --flake8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
