[tool.poetry]
name = "chartisan"
version = "1.1.1"
description = "Chartisan's Python backend"
authors = ["Erik Campobadal <soc@erik.cat>"]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
